### ISSUE TITLE
Improve registration form

### ISSUE THREAD

**Issue by floriandriessen** [nova-postdoc-retreat/nova-postdoc-retreat.github.io#3]
- send e-mail when registration finished or give some other confirmation to user the registration went successful
- see if form can be made in better format
- see if affiliations can be given as bullet point list or sort a like in order to have some default choices
- ensure that form only submits when all required fields are filled in

**Comment by svaberg** [comment]
Most of this is done but the 'Affiliation' drop-down looks a bit wonky. Also I'm not sure how to send an email yet.

**Comment by svaberg** [comment]
I think this is ok for now.

**Comment by floriandriessen** [comment]
Yes looks good. Keep in mind ESA is not included; affiliations to be inserted in the future:

- Leiden Observatory
- Astronomical Institute Anton Pannekoek
- Kapteyn Institute
- IMAPP Nijmegen
- SRON
- ASTRON
- TU Delft

**Comment by svaberg** [comment]
Pancakes!

**Comment by svaberg** [comment]
I figured out how to automate emails but they will be from me (dag.evensberget@gmail.com) which is perhaps not ideal. I think to work around this we would have to use another service than Google or create a Google account for the event. I'm not sure about Google's policy for non-personal accounts.

**Comment by floriandriessen** [comment]
Resolved in pull request #15, #20, and #21.
